[package]
name = "day-01-star-2"
version = "0.1.0"
authors = ["Max Jacobson <max@hardscrabble.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
